apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: delivery
type: Opaque
stringData:
  DB_URL: localhost-secret-test
  DB_USER: admin-secret-test
#data: # value부분을 base64인코딩 처리
  #password: test-password
